luettavat_arvot = []

luettavat_arvot.append("fbAnaIn_Grease PR311 L2")
luettavat_arvot.append("fbAnaIn_Pressing nip PR311")
luettavat_arvot.append("fbDirectDrive_Hyd_Motor")
luettavat_arvot.append("fbDirectDrive_HydCooler")
luettavat_arvot.append("fbDirectDrive_HydHeating")
luettavat_arvot.append("fbValve_301_Press")
luettavat_arvot.append("fbValve_Lube_A")
luettavat_arvot.append("fbValve_Lube_B")
luettavat_arvot.append("fbValve_PR301 floating piston")
luettavat_arvot.append("fbValve_PR301 floating safety")
luettavat_arvot.append("fbValve_PR311 floating piston")
luettavat_arvot.append("fbValve_PR311 floating shaft safety")
luettavat_arvot.append("fbDistributionscrew_SCR200")
luettavat_arvot.append("fbLowerPressRoll_PR301")
luettavat_arvot.append("fbUpperPressRoll_PR301")
luettavat_arvot.append("fbAuxiliarydrive_PR301")
luettavat_arvot.append("fbAirBlower_PR311")
luettavat_arvot.append("fbEffluentfilterscraper_SCA312")
luettavat_arvot.append("fbDischargeScrew_SCR313")
luettavat_arvot.append("fbSpillageliftingscraperconveyor_SCA501")
luettavat_arvot.append("fbSpillagescraperconveyor_SCA500")
luettavat_arvot.append("fbAnaIn_Oil temperature")
luettavat_arvot.append("fbAnaIn_Oil level")
luettavat_arvot.append("fbAnaIn_Pressure line PR311")
luettavat_arvot.append("fbAnaIn_Pressure line PR301")
luettavat_arvot.append("fbAnaIn_Grease PR301 L1")
luettavat_arvot.append("fbAnaIn_Grease PR301 L2")
